# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from macfleet.comm.proto import control_pb2 as control__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClusterControlStub(object):
    """Main cluster control service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/macfleet.ClusterControl/Register',
                request_serializer=control__pb2.RegisterRequest.SerializeToString,
                response_deserializer=control__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/macfleet.ClusterControl/Heartbeat',
                request_serializer=control__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=control__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.SyncBarrier = channel.unary_unary(
                '/macfleet.ClusterControl/SyncBarrier',
                request_serializer=control__pb2.BarrierRequest.SerializeToString,
                response_deserializer=control__pb2.BarrierResponse.FromString,
                _registered_method=True)
        self.StartTraining = channel.unary_unary(
                '/macfleet.ClusterControl/StartTraining',
                request_serializer=control__pb2.TrainingConfigProto.SerializeToString,
                response_deserializer=control__pb2.Ack.FromString,
                _registered_method=True)
        self.StopTraining = channel.unary_unary(
                '/macfleet.ClusterControl/StopTraining',
                request_serializer=control__pb2.StopRequest.SerializeToString,
                response_deserializer=control__pb2.Ack.FromString,
                _registered_method=True)
        self.GetClusterState = channel.unary_unary(
                '/macfleet.ClusterControl/GetClusterState',
                request_serializer=control__pb2.Empty.SerializeToString,
                response_deserializer=control__pb2.ClusterStateProto.FromString,
                _registered_method=True)
        self.Broadcast = channel.unary_unary(
                '/macfleet.ClusterControl/Broadcast',
                request_serializer=control__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=control__pb2.Ack.FromString,
                _registered_method=True)


class ClusterControlServicer(object):
    """Main cluster control service
    """

    def Register(self, request, context):
        """Node registration with the coordinator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Periodic heartbeat from workers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncBarrier(self, request, context):
        """Synchronization barrier for distributed training
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTraining(self, request, context):
        """Start distributed training
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTraining(self, request, context):
        """Stop distributed training
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterState(self, request, context):
        """Get current cluster state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Broadcast(self, request, context):
        """Broadcast message to all nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=control__pb2.RegisterRequest.FromString,
                    response_serializer=control__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=control__pb2.HeartbeatRequest.FromString,
                    response_serializer=control__pb2.HeartbeatResponse.SerializeToString,
            ),
            'SyncBarrier': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncBarrier,
                    request_deserializer=control__pb2.BarrierRequest.FromString,
                    response_serializer=control__pb2.BarrierResponse.SerializeToString,
            ),
            'StartTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=control__pb2.TrainingConfigProto.FromString,
                    response_serializer=control__pb2.Ack.SerializeToString,
            ),
            'StopTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTraining,
                    request_deserializer=control__pb2.StopRequest.FromString,
                    response_serializer=control__pb2.Ack.SerializeToString,
            ),
            'GetClusterState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterState,
                    request_deserializer=control__pb2.Empty.FromString,
                    response_serializer=control__pb2.ClusterStateProto.SerializeToString,
            ),
            'Broadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.Broadcast,
                    request_deserializer=control__pb2.BroadcastRequest.FromString,
                    response_serializer=control__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'macfleet.ClusterControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('macfleet.ClusterControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClusterControl(object):
    """Main cluster control service
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macfleet.ClusterControl/Register',
            control__pb2.RegisterRequest.SerializeToString,
            control__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macfleet.ClusterControl/Heartbeat',
            control__pb2.HeartbeatRequest.SerializeToString,
            control__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncBarrier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macfleet.ClusterControl/SyncBarrier',
            control__pb2.BarrierRequest.SerializeToString,
            control__pb2.BarrierResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macfleet.ClusterControl/StartTraining',
            control__pb2.TrainingConfigProto.SerializeToString,
            control__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macfleet.ClusterControl/StopTraining',
            control__pb2.StopRequest.SerializeToString,
            control__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macfleet.ClusterControl/GetClusterState',
            control__pb2.Empty.SerializeToString,
            control__pb2.ClusterStateProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Broadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macfleet.ClusterControl/Broadcast',
            control__pb2.BroadcastRequest.SerializeToString,
            control__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
